/** CRADY Portfolio Analyzer Phase 1 — rule-based Quick Report.
 *
 * Every sentence is templated from real numbers already computed by
 * lib/portfolio/calculations.ts — nothing here is generated by a model,
 * and nothing here issues a buy/sell instruction or a confident forecast
 * (matches the site's existing disclaimer language, see lib/eeat.ts). */

export type QuickReportHolding = {
  ticker: string;
  /** Display label (e.g. "YieldMax"), not the raw provider_id slug — the
   * concentration sentence renders this verbatim. Callers must run it
   * through lib/providers.ts's providerLabel() before passing it in. */
  providerId: string;
  investmentAmount: number;
  totalReturnAmount: number | null;
  priceStatus: "current" | "delayed" | "incomplete" | "estimated" | "unavailable";
  priceStaleDays: number | null;
  hasSplitWarning: boolean;
};

export type QuickReportAlternative = {
  forTicker: string;
  altTicker: string;
  deltaAmount: number; // alternative total-return $ minus the real holding's total-return $
};

export type QuickReportInput = {
  holdings: QuickReportHolding[];
  totalInvested: number;
  totalCurrentValue: number;
  totalDividendsReceived: number;
  totalPriceReturnAmount: number;
  totalReturnAmount: number;
  totalReturnPct: number | null;
  /** The single most favorable real alternative found across all holdings,
   * if any (chosen by the caller — this module doesn't rank alternatives
   * itself, see lib/portfolio/alternativePicks.ts). */
  bestAlternative?: QuickReportAlternative | null;
};

function fmtMoney(n: number): string {
  const sign = n < 0 ? "-" : "";
  return `${sign}$${Math.abs(n).toLocaleString("en-US", { maximumFractionDigits: 0 })}`;
}

function fmtPct(n: number): string {
  const sign = n >= 0 ? "+" : "";
  return `${sign}${n.toFixed(1)}%`;
}

const T = {
  summaryGain: {
    en: (div: string, price: string, total: string, pct: string) =>
      `Your portfolio has received ${div} in distributions, and price changes of ${price} bring the total result to ${total} (${pct}).`,
    ko: (div: string, price: string, total: string, pct: string) =>
      `포트폴리오는 ${div}의 배당금을 받았으며, ${price}의 가격 변동을 반영한 총수익은 ${total}(${pct})입니다.`,
  },
  summaryLoss: {
    en: (div: string, price: string, total: string, pct: string) =>
      `Your portfolio has received ${div} in distributions, but price declines of ${price} leave the position with a total loss of ${total} (${pct}).`,
    ko: (div: string, price: string, total: string, pct: string) =>
      `포트폴리오는 ${div}의 배당금을 받았지만, ${price}의 가격 하락으로 총 손실 ${total}(${pct})을 기록하고 있습니다.`,
  },
  offset: {
    en: (pct: string) => `Distributions have offset approximately ${pct} of the price decline.`,
    ko: (pct: string) => `배당금이 가격 하락분의 약 ${pct}를 상쇄했습니다.`,
  },
  bestContributor: {
    en: (t: string, amt: string) => `${t} is your strongest contributor, adding ${amt} in total return.`,
    ko: (t: string, amt: string) => `${t}가 총수익에 ${amt}로 가장 크게 기여했습니다.`,
  },
  worstContributor: {
    en: (t: string, amt: string) => `${t} is your weakest contributor, at ${amt} in total return.`,
    ko: (t: string, amt: string) => `${t}는 총수익 ${amt}로 가장 부진한 종목입니다.`,
  },
  concentration: {
    en: (pct: string, provider: string) =>
      `Approximately ${pct} of your invested capital is in ${provider} products, creating issuer concentration risk.`,
    ko: (pct: string, provider: string) => `투자 자본의 약 ${pct}가 ${provider} 상품에 집중되어 있어 발행사 집중 위험이 있습니다.`,
  },
  alternativeBetter: {
    en: (alt: string, t: string, amt: string) =>
      `The same investment in ${alt} on the same purchase date would currently show a total return ${amt} higher than your ${t} position.`,
    ko: (alt: string, t: string, amt: string) =>
      `같은 날짜에 동일 금액을 ${alt}에 투자했다면 ${t} 대비 총수익이 ${amt} 더 높았을 것으로 계산됩니다.`,
  },
  alternativeWorse: {
    en: (alt: string, t: string, amt: string) =>
      `The same investment in ${alt} on the same purchase date would currently show a total return ${amt} lower than your ${t} position.`,
    ko: (alt: string, t: string, amt: string) =>
      `같은 날짜에 동일 금액을 ${alt}에 투자했다면 ${t} 대비 총수익이 ${amt} 더 낮았을 것으로 계산됩니다.`,
  },
  staleData: {
    en: (t: string, days: number) => `${t}'s latest price is ${days} days old — treat its current value with caution.`,
    ko: (t: string, days: number) => `${t}의 최신 가격은 ${days}일 전 데이터로, 현재 평가금액은 참고용으로만 확인하십시오.`,
  },
  splitWarning: {
    en: (t: string) => `${t} shows an unusually large single-day price change that may reflect an unrecorded stock split — its return figures may be inaccurate.`,
    ko: (t: string) => `${t}는 하루 사이 이례적으로 큰 가격 변동을 보여 미반영된 액면분할일 가능성이 있으며, 수익률 수치가 부정확할 수 있습니다.`,
  },
  genericCheck: {
    en: "Review the full breakdown above before drawing any conclusions — this report is informational, not investment advice.",
    ko: "결론을 내리기 전에 위의 상세 내역을 확인하십시오 — 이 리포트는 정보 제공 목적이며 투자 조언이 아닙니다.",
  },
} as const;

const CONCENTRATION_THRESHOLD_PCT = 50;

export function buildQuickReport(input: QuickReportInput, lang: "en" | "ko" = "en"): string[] {
  const sentences: string[] = [];
  const {
    holdings,
    totalInvested,
    totalDividendsReceived,
    totalPriceReturnAmount,
    totalReturnAmount,
    totalReturnPct,
    bestAlternative,
  } = input;

  if (totalReturnPct == null) return sentences;

  // 1. Overall summary — price and dividend components always shown
  // separately, per the site's established discipline (see EtfHero's
  // Price vs Dividend split).
  const divStr = fmtMoney(totalDividendsReceived);
  const priceStr = fmtMoney(totalPriceReturnAmount);
  const totalStr = fmtMoney(totalReturnAmount);
  const pctStr = fmtPct(totalReturnPct);
  sentences.push(
    totalReturnAmount >= 0
      ? T.summaryGain[lang](divStr, priceStr, totalStr, pctStr)
      : T.summaryLoss[lang](divStr, priceStr, totalStr, pctStr)
  );

  // 2. Offset relationship — only meaningful when there's a real price
  // decline to offset.
  if (totalPriceReturnAmount < 0 && totalDividendsReceived > 0) {
    const offsetPct = Math.min(100, (totalDividendsReceived / Math.abs(totalPriceReturnAmount)) * 100);
    sentences.push(T.offset[lang](`${offsetPct.toFixed(0)}%`));
  }

  // 3/4. Best/worst contributor — only meaningful across multiple holdings.
  if (holdings.length > 1) {
    const withReturn = holdings.filter((h) => h.totalReturnAmount != null) as (QuickReportHolding & {
      totalReturnAmount: number;
    })[];
    if (withReturn.length > 1) {
      const best = withReturn.reduce((a, b) => (b.totalReturnAmount > a.totalReturnAmount ? b : a));
      const worst = withReturn.reduce((a, b) => (b.totalReturnAmount < a.totalReturnAmount ? b : a));
      if (best.ticker !== worst.ticker) {
        sentences.push(T.bestContributor[lang](best.ticker, fmtMoney(best.totalReturnAmount)));
        sentences.push(T.worstContributor[lang](worst.ticker, fmtMoney(worst.totalReturnAmount)));
      }
    }
  }

  // 5. Provider concentration.
  if (totalInvested > 0) {
    const byProvider = new Map<string, number>();
    for (const h of holdings) {
      byProvider.set(h.providerId, (byProvider.get(h.providerId) ?? 0) + h.investmentAmount);
    }
    for (const [providerId, amount] of byProvider) {
      const pct = (amount / totalInvested) * 100;
      if (pct >= CONCENTRATION_THRESHOLD_PCT) {
        sentences.push(T.concentration[lang](`${pct.toFixed(0)}%`, providerId));
        break; // one concentration sentence is enough
      }
    }
  }

  // 6. Alternative comparison.
  if (bestAlternative) {
    const amt = fmtMoney(Math.abs(bestAlternative.deltaAmount));
    sentences.push(
      bestAlternative.deltaAmount > 0
        ? T.alternativeBetter[lang](bestAlternative.altTicker, bestAlternative.forTicker, amt)
        : T.alternativeWorse[lang](bestAlternative.altTicker, bestAlternative.forTicker, amt)
    );
  }

  // 7. Data-quality flags the user should specifically check.
  for (const h of holdings) {
    if (h.priceStatus === "delayed" && h.priceStaleDays != null) {
      sentences.push(T.staleData[lang](h.ticker, h.priceStaleDays));
    }
    if (h.hasSplitWarning) {
      sentences.push(T.splitWarning[lang](h.ticker));
    }
  }

  sentences.push(T.genericCheck[lang]);

  return sentences;
}
